name: Build

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can use windows-latest or macos-latest if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

