name: Build and Release .NET 8 by Tag
on:
  push:
    tags:
      - "v*"  # Triggers when a tag like v1.0.0 is pushed

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./AzureDailyCostCompare/AzureDailyCostCompare.csproj

      - name: Publish project (Linux)
        run: dotnet publish ./AzureDailyCostCompare/AzureDailyCostCompare.csproj -r linux-x64 --self-contained true --configuration Release --output ./publish

      - name: Archive build artifacts (Linux)
        run: |
          tar -czvf AzureDailyCostCompare-${{ github.ref_name }}-linux-x64.tar.gz -C ./publish .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzureDailyCostCompare-${{ github.ref_name }}-linux-x64
          path: AzureDailyCostCompare-${{ github.ref_name }}-linux-x64.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./AzureDailyCostCompare/AzureDailyCostCompare.csproj

      - name: Publish project (Windows)
        run: dotnet publish ./AzureDailyCostCompare/AzureDailyCostCompare.csproj -r win-x64 --self-contained true --configuration Release --output ./publish

      - name: Archive build artifacts (Windows)
        run: |
          powershell Compress-Archive -Path ./publish/* -DestinationPath AzureDailyCostCompare-${{ github.ref_name }}-win-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzureDailyCostCompare-${{ github.ref_name }}-win-x64
          path: AzureDailyCostCompare-${{ github.ref_name }}-win-x64.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./AzureDailyCostCompare/AzureDailyCostCompare.csproj

      - name: Publish project (macOS)
        run: dotnet publish ./AzureDailyCostCompare/AzureDailyCostCompare.csproj -r osx-x64 --self-contained true --configuration Release --output ./publish

      - name: Archive build artifacts (macOS)
        run: |
          tar -czvf AzureDailyCostCompare-${{ github.ref_name }}-osx-x64.tar.gz -C ./publish .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzureDailyCostCompare-${{ github.ref_name }}-osx-x64
          path: AzureDailyCostCompare-${{ github.ref_name }}-osx-x64.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]  # Ensures all build jobs finish before the release job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download build artifacts from all platforms
      - name: Download build artifacts (Linux)
        uses: actions/download-artifact@v3
        with:
          name: AzureDailyCostCompare-${{ github.ref_name }}-linux-x64

      - name: Download build artifacts (Windows)
        uses: actions/download-artifact@v3
        with:
          name: AzureDailyCostCompare-${{ github.ref_name }}-win-x64

      - name: Download build artifacts (macOS)
        uses: actions/download-artifact@v3
        with:
          name: AzureDailyCostCompare-${{ github.ref_name }}-osx-x64

      # Create GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            AzureDailyCostCompare-${{ github.ref_name }}-linux-x64.tar.gz
            AzureDailyCostCompare-${{ github.ref_name }}-win-x64.zip
            AzureDailyCostCompare-${{ github.ref_name }}-osx-x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
